package io.minhasaude.msapi.model;

public enum GrauEscolaridade {

	FUNDAMENTAL_INCOMPLETO, FUNDAMENTAL_COMPLETO, MEDIO_INCOMPLETO, MEDIO_COMPLETO, SUPERIOR_INCOMPLETO, SUPERIOR_COMPLETO, MESTRADO, DOUTORADO, POS_DOUTORADO;
}
